apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gx21
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gx21
    app.kubernetes.io/part-of: tkrw-pr714-0075-0013-app
  name: devfile-sample-gx21
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gx21
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gx21
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0013-tenant/tkrw-pr714-0075-0013-app/devfile-sample-gx21@sha256:ef067fd8be2bc8f7ddbe41e60d060867b6b6ce1efe070ae61ce78fbf2fda49cb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
